### ISSUE TITLE
Seed param not doing anything

### ISSUE THREAD

**Issue by pimepan** [Jsoto22/value-noise-js#1]
I am generating a 2d grid and filling it with the noise values. Even tho i am creating a new ValueNoise instance with "mySeed" as param, every time i refresh the result is different. code example below:
 ```javascript
let grid = [];
//NOISE INSTANCED HERE
  const noise = new ValueNoise('myseed')
  const gridSize = world.gridSize;
  for (let i = 0; i < world.wx / gridSize; i++) {
    grid[i] = [];
    for (let j = 0; j < world.wy / gridSize; j++) {
      const x = i * gridSize;
      const y = j * gridSize;
      // NOISE EVALUATED HERE
      const noiseVal = noise.evalXY(x,y);

      console.log(noiseVal);
      const cell = new GridCell({
        x,
        y,
        w: gridSize,
        h: gridSize,
        tileType: tileRanges(noiseVal),
      });
      grid[i][j] = cell;
    }
  }
```
every time i refreshed the logged values are different. maybe i am missing something?

**Comment by Jsoto22** [comment]
Sorry for responding late. I'll look into this over the weekend.

**Comment by Jsoto22** [comment]
@pimepan Just did some light testing and I believe it has to do with how the permutation is shuffled. I'll publish a patch soon where it uses the seed provided for that. Good catch btw.

**Comment by Jsoto22** [comment]
@pimepan Just pushed a patch and published to npm. Let me know if it's resolved for you so I can close this issue.
